root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'solid'
extends: 
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:solid/typescript'
  - 'prettier'
env:
  browser: true
  node: true
